"""Generated message classes for appengine version v1beta4.

The App Engine Admin API enables developers to provision and manage their App
Engine applications.
"""
# NOTE: This file is autogenerated and should not be edited by hand.

from protorpc import messages as _messages

from googlecloudapis.apitools.base.py import encoding


package = 'appengine'


class ApiConfigHandler(_messages.Message):
  """A ApiConfigHandler object.

  Enums:
    AuthFailActionValueValuesEnum:
    LoginValueValuesEnum:
    SecurityLevelValueValuesEnum:

  Fields:
    authFailAction: A AuthFailActionValueValuesEnum attribute.
    login: A LoginValueValuesEnum attribute.
    script: A string attribute.
    securityLevel: A SecurityLevelValueValuesEnum attribute.
    url: A string attribute.
  """

  class AuthFailActionValueValuesEnum(_messages.Enum):
    """AuthFailActionValueValuesEnum enum type.

    Values:
      AUTH_FAIL_ACTION_REDIRECT: <no description>
      AUTH_FAIL_ACTION_UNAUTHORIZED: <no description>
      AUTH_FAIL_ACTION_UNSPECIFIED: <no description>
    """
    AUTH_FAIL_ACTION_REDIRECT = 0
    AUTH_FAIL_ACTION_UNAUTHORIZED = 1
    AUTH_FAIL_ACTION_UNSPECIFIED = 2

  class LoginValueValuesEnum(_messages.Enum):
    """LoginValueValuesEnum enum type.

    Values:
      LOGIN_ADMIN: <no description>
      LOGIN_OPTIONAL: <no description>
      LOGIN_REQUIRED: <no description>
      LOGIN_UNSPECIFIED: <no description>
    """
    LOGIN_ADMIN = 0
    LOGIN_OPTIONAL = 1
    LOGIN_REQUIRED = 2
    LOGIN_UNSPECIFIED = 3

  class SecurityLevelValueValuesEnum(_messages.Enum):
    """SecurityLevelValueValuesEnum enum type.

    Values:
      SECURE_ALWAYS: <no description>
      SECURE_DEFAULT: <no description>
      SECURE_NEVER: <no description>
      SECURE_OPTIONAL: <no description>
      SECURE_UNSPECIFIED: <no description>
    """
    SECURE_ALWAYS = 0
    SECURE_DEFAULT = 1
    SECURE_NEVER = 2
    SECURE_OPTIONAL = 3
    SECURE_UNSPECIFIED = 4

  authFailAction = _messages.EnumField('AuthFailActionValueValuesEnum', 1)
  login = _messages.EnumField('LoginValueValuesEnum', 2)
  script = _messages.StringField(3)
  securityLevel = _messages.EnumField('SecurityLevelValueValuesEnum', 4)
  url = _messages.StringField(5)


class ApiEndpointHandler(_messages.Message):
  """A ApiEndpointHandler object.

  Fields:
    scriptPath: A string attribute.
  """

  scriptPath = _messages.StringField(1)


class AppengineAppsCreateRequest(_messages.Message):
  """A AppengineAppsCreateRequest object.

  Fields:
    application: A Application resource to be passed as the request body.
  """

  application = _messages.MessageField('Application', 1)


class AppengineAppsEmailSendersCreateRequest(_messages.Message):
  """A AppengineAppsEmailSendersCreateRequest object.

  Fields:
    emailSender: A EmailSender resource to be passed as the request body.
    name: A string attribute.
  """

  emailSender = _messages.MessageField('EmailSender', 1)
  name = _messages.StringField(2, required=True)


class AppengineAppsEmailSendersDeleteRequest(_messages.Message):
  """A AppengineAppsEmailSendersDeleteRequest object.

  Fields:
    name: A string attribute.
  """

  name = _messages.StringField(1, required=True)


class AppengineAppsEmailSendersListRequest(_messages.Message):
  """A AppengineAppsEmailSendersListRequest object.

  Fields:
    name: A string attribute.
    pageSize: A integer attribute.
    pageToken: A string attribute.
  """

  name = _messages.StringField(1, required=True)
  pageSize = _messages.IntegerField(2, variant=_messages.Variant.INT32)
  pageToken = _messages.StringField(3)


class AppengineAppsGetIamPolicyRequest(_messages.Message):
  """A AppengineAppsGetIamPolicyRequest object.

  Fields:
    resource: A string attribute.
  """

  resource = _messages.StringField(1, required=True)


class AppengineAppsGetRequest(_messages.Message):
  """A AppengineAppsGetRequest object.

  Fields:
    ensureResourcesExist: A boolean attribute.
    name: A string attribute.
  """

  ensureResourcesExist = _messages.BooleanField(1)
  name = _messages.StringField(2, required=True)


class AppengineAppsModulesDeleteRequest(_messages.Message):
  """A AppengineAppsModulesDeleteRequest object.

  Fields:
    name: A string attribute.
  """

  name = _messages.StringField(1, required=True)


class AppengineAppsModulesGetIamPolicyRequest(_messages.Message):
  """A AppengineAppsModulesGetIamPolicyRequest object.

  Fields:
    getIamPolicyRequest: A GetIamPolicyRequest resource to be passed as the
      request body.
    resource: A string attribute.
  """

  getIamPolicyRequest = _messages.MessageField('GetIamPolicyRequest', 1)
  resource = _messages.StringField(2, required=True)


class AppengineAppsModulesGetRequest(_messages.Message):
  """A AppengineAppsModulesGetRequest object.

  Fields:
    name: A string attribute.
  """

  name = _messages.StringField(1, required=True)


class AppengineAppsModulesListRequest(_messages.Message):
  """A AppengineAppsModulesListRequest object.

  Fields:
    name: A string attribute.
    pageSize: A integer attribute.
    pageToken: A string attribute.
  """

  name = _messages.StringField(1, required=True)
  pageSize = _messages.IntegerField(2, variant=_messages.Variant.INT32)
  pageToken = _messages.StringField(3)


class AppengineAppsModulesPatchRequest(_messages.Message):
  """A AppengineAppsModulesPatchRequest object.

  Fields:
    mask: A string attribute.
    migrateTraffic: A boolean attribute.
    module: A Module resource to be passed as the request body.
    name: A string attribute.
  """

  mask = _messages.StringField(1)
  migrateTraffic = _messages.BooleanField(2)
  module = _messages.MessageField('Module', 3)
  name = _messages.StringField(4, required=True)


class AppengineAppsModulesSetIamPolicyRequest(_messages.Message):
  """A AppengineAppsModulesSetIamPolicyRequest object.

  Fields:
    resource: A string attribute.
    setIamPolicyRequest: A SetIamPolicyRequest resource to be passed as the
      request body.
  """

  resource = _messages.StringField(1, required=True)
  setIamPolicyRequest = _messages.MessageField('SetIamPolicyRequest', 2)


class AppengineAppsModulesVersionsCreateRequest(_messages.Message):
  """A AppengineAppsModulesVersionsCreateRequest object.

  Fields:
    name: A string attribute.
    version: A Version resource to be passed as the request body.
  """

  name = _messages.StringField(1, required=True)
  version = _messages.MessageField('Version', 2)


class AppengineAppsModulesVersionsDeleteRequest(_messages.Message):
  """A AppengineAppsModulesVersionsDeleteRequest object.

  Fields:
    name: A string attribute.
  """

  name = _messages.StringField(1, required=True)


class AppengineAppsModulesVersionsGetRequest(_messages.Message):
  """A AppengineAppsModulesVersionsGetRequest object.

  Enums:
    ViewValueValuesEnum:

  Fields:
    name: A string attribute.
    view: A ViewValueValuesEnum attribute.
  """

  class ViewValueValuesEnum(_messages.Enum):
    """ViewValueValuesEnum enum type.

    Values:
      BASIC: <no description>
      FULL: <no description>
    """
    BASIC = 0
    FULL = 1

  name = _messages.StringField(1, required=True)
  view = _messages.EnumField('ViewValueValuesEnum', 2)


class AppengineAppsModulesVersionsListRequest(_messages.Message):
  """A AppengineAppsModulesVersionsListRequest object.

  Enums:
    ViewValueValuesEnum:

  Fields:
    name: A string attribute.
    pageSize: A integer attribute.
    pageToken: A string attribute.
    view: A ViewValueValuesEnum attribute.
  """

  class ViewValueValuesEnum(_messages.Enum):
    """ViewValueValuesEnum enum type.

    Values:
      BASIC: <no description>
      FULL: <no description>
    """
    BASIC = 0
    FULL = 1

  name = _messages.StringField(1, required=True)
  pageSize = _messages.IntegerField(2, variant=_messages.Variant.INT32)
  pageToken = _messages.StringField(3)
  view = _messages.EnumField('ViewValueValuesEnum', 4)


class AppengineAppsOperationsCancelRequest(_messages.Message):
  """A AppengineAppsOperationsCancelRequest object.

  Fields:
    cancelOperationRequest: A CancelOperationRequest resource to be passed as
      the request body.
    name: A string attribute.
  """

  cancelOperationRequest = _messages.MessageField('CancelOperationRequest', 1)
  name = _messages.StringField(2, required=True)


class AppengineAppsOperationsDeleteRequest(_messages.Message):
  """A AppengineAppsOperationsDeleteRequest object.

  Fields:
    name: A string attribute.
  """

  name = _messages.StringField(1, required=True)


class AppengineAppsOperationsGetRequest(_messages.Message):
  """A AppengineAppsOperationsGetRequest object.

  Fields:
    name: A string attribute.
  """

  name = _messages.StringField(1, required=True)


class AppengineAppsOperationsListRequest(_messages.Message):
  """A AppengineAppsOperationsListRequest object.

  Fields:
    filter: A string attribute.
    name: A string attribute.
    pageSize: A integer attribute.
    pageToken: A string attribute.
  """

  filter = _messages.StringField(1)
  name = _messages.StringField(2, required=True)
  pageSize = _messages.IntegerField(3, variant=_messages.Variant.INT32)
  pageToken = _messages.StringField(4)


class AppengineAppsPatchRequest(_messages.Message):
  """A AppengineAppsPatchRequest object.

  Fields:
    application: A Application resource to be passed as the request body.
    mask: A string attribute.
    name: A string attribute.
  """

  application = _messages.MessageField('Application', 1)
  mask = _messages.StringField(2)
  name = _messages.StringField(3, required=True)


class AppengineAppsSetIamPolicyRequest(_messages.Message):
  """A AppengineAppsSetIamPolicyRequest object.

  Fields:
    resource: A string attribute.
    setIamPolicyRequest: A SetIamPolicyRequest resource to be passed as the
      request body.
  """

  resource = _messages.StringField(1, required=True)
  setIamPolicyRequest = _messages.MessageField('SetIamPolicyRequest', 2)


class Application(_messages.Message):
  """A Application object.

  Fields:
    authDomain: A string attribute.
    blockedAddresses: A string attribute.
    codeBucket: A string attribute.
    dispatchRules: A UrlDispatchRule attribute.
    domains: A string attribute.
    id: A string attribute.
    location: A string attribute.
    name: A string attribute.
  """

  authDomain = _messages.StringField(1)
  blockedAddresses = _messages.StringField(2, repeated=True)
  codeBucket = _messages.StringField(3)
  dispatchRules = _messages.MessageField('UrlDispatchRule', 4, repeated=True)
  domains = _messages.StringField(5, repeated=True)
  id = _messages.StringField(6)
  location = _messages.StringField(7)
  name = _messages.StringField(8)


class AutomaticScaling(_messages.Message):
  """A AutomaticScaling object.

  Fields:
    coolDownPeriod: A string attribute.
    cpuUtilization: A CpuUtilization attribute.
    maxConcurrentRequests: A integer attribute.
    maxIdleInstances: A integer attribute.
    maxPendingLatency: A string attribute.
    maxTotalInstances: A integer attribute.
    minIdleInstances: A integer attribute.
    minPendingLatency: A string attribute.
    minTotalInstances: A integer attribute.
  """

  coolDownPeriod = _messages.StringField(1)
  cpuUtilization = _messages.MessageField('CpuUtilization', 2)
  maxConcurrentRequests = _messages.IntegerField(3, variant=_messages.Variant.INT32)
  maxIdleInstances = _messages.IntegerField(4, variant=_messages.Variant.INT32)
  maxPendingLatency = _messages.StringField(5)
  maxTotalInstances = _messages.IntegerField(6, variant=_messages.Variant.INT32)
  minIdleInstances = _messages.IntegerField(7, variant=_messages.Variant.INT32)
  minPendingLatency = _messages.StringField(8)
  minTotalInstances = _messages.IntegerField(9, variant=_messages.Variant.INT32)


class BasicScaling(_messages.Message):
  """A BasicScaling object.

  Fields:
    idleTimeout: A string attribute.
    maxInstances: A integer attribute.
  """

  idleTimeout = _messages.StringField(1)
  maxInstances = _messages.IntegerField(2, variant=_messages.Variant.INT32)


class Binding(_messages.Message):
  """A Binding object.

  Fields:
    members: A string attribute.
    role: A string attribute.
  """

  members = _messages.StringField(1, repeated=True)
  role = _messages.StringField(2)


class CancelOperationRequest(_messages.Message):
  """A CancelOperationRequest object."""


class CloudAuditOptions(_messages.Message):
  """A CloudAuditOptions object."""


class Condition(_messages.Message):
  """A Condition object.

  Enums:
    IamValueValuesEnum:
    OpValueValuesEnum:

  Fields:
    iam: A IamValueValuesEnum attribute.
    op: A OpValueValuesEnum attribute.
    svc: A string attribute.
    sys: A string attribute.
    value: A string attribute.
    values: A string attribute.
  """

  class IamValueValuesEnum(_messages.Enum):
    """IamValueValuesEnum enum type.

    Values:
      ATTRIBUTION: <no description>
      AUTHORITY: <no description>
      NO_ATTR: <no description>
    """
    ATTRIBUTION = 0
    AUTHORITY = 1
    NO_ATTR = 2

  class OpValueValuesEnum(_messages.Enum):
    """OpValueValuesEnum enum type.

    Values:
      DISCHARGED: <no description>
      EQUALS: <no description>
      IN: <no description>
      NOT_EQUALS: <no description>
      NOT_IN: <no description>
      NO_OP: <no description>
    """
    DISCHARGED = 0
    EQUALS = 1
    IN = 2
    NOT_EQUALS = 3
    NOT_IN = 4
    NO_OP = 5

  iam = _messages.EnumField('IamValueValuesEnum', 1)
  op = _messages.EnumField('OpValueValuesEnum', 2)
  svc = _messages.StringField(3)
  sys = _messages.StringField(4)
  value = _messages.StringField(5)
  values = _messages.StringField(6, repeated=True)


class ContainerInfo(_messages.Message):
  """A ContainerInfo object.

  Fields:
    image: A string attribute.
    sha256: A string attribute.
  """

  image = _messages.StringField(1)
  sha256 = _messages.StringField(2)


class CounterOptions(_messages.Message):
  """A CounterOptions object.

  Fields:
    field: A string attribute.
    metric: A string attribute.
  """

  field = _messages.StringField(1)
  metric = _messages.StringField(2)


class CpuUtilization(_messages.Message):
  """A CpuUtilization object.

  Fields:
    aggregationWindowLength: A string attribute.
    targetUtilization: A number attribute.
  """

  aggregationWindowLength = _messages.StringField(1)
  targetUtilization = _messages.FloatField(2)


class DataAccessOptions(_messages.Message):
  """A DataAccessOptions object."""


class Deployment(_messages.Message):
  """A Deployment object.

  Messages:
    FilesValue: A FilesValue object.

  Fields:
    container: A ContainerInfo attribute.
    files: A FilesValue attribute.
    sourceReferences: A SourceReference attribute.
  """

  @encoding.MapUnrecognizedFields('additionalProperties')
  class FilesValue(_messages.Message):
    """A FilesValue object.

    Messages:
      AdditionalProperty: An additional property for a FilesValue object.

    Fields:
      additionalProperties: Additional properties of type FilesValue
    """

    class AdditionalProperty(_messages.Message):
      """An additional property for a FilesValue object.

      Fields:
        key: Name of the additional property.
        value: A FileInfo attribute.
      """

      key = _messages.StringField(1)
      value = _messages.MessageField('FileInfo', 2)

    additionalProperties = _messages.MessageField('AdditionalProperty', 1, repeated=True)

  container = _messages.MessageField('ContainerInfo', 1)
  files = _messages.MessageField('FilesValue', 2)
  sourceReferences = _messages.MessageField('SourceReference', 3, repeated=True)


class EmailSender(_messages.Message):
  """A EmailSender object.

  Fields:
    address: A string attribute.
    name: A string attribute.
  """

  address = _messages.StringField(1)
  name = _messages.StringField(2)


class Empty(_messages.Message):
  """A Empty object."""


class ErrorHandler(_messages.Message):
  """A ErrorHandler object.

  Enums:
    ErrorCodeValueValuesEnum:

  Fields:
    errorCode: A ErrorCodeValueValuesEnum attribute.
    mimeType: A string attribute.
    staticFile: A string attribute.
  """

  class ErrorCodeValueValuesEnum(_messages.Enum):
    """ErrorCodeValueValuesEnum enum type.

    Values:
      ERROR_CODE_DEFAULT: <no description>
      ERROR_CODE_DOS_API_DENIAL: <no description>
      ERROR_CODE_OVER_QUOTA: <no description>
      ERROR_CODE_TIMEOUT: <no description>
      ERROR_CODE_UNSPECIFIED: <no description>
    """
    ERROR_CODE_DEFAULT = 0
    ERROR_CODE_DOS_API_DENIAL = 1
    ERROR_CODE_OVER_QUOTA = 2
    ERROR_CODE_TIMEOUT = 3
    ERROR_CODE_UNSPECIFIED = 4

  errorCode = _messages.EnumField('ErrorCodeValueValuesEnum', 1)
  mimeType = _messages.StringField(2)
  staticFile = _messages.StringField(3)


class FileInfo(_messages.Message):
  """A FileInfo object.

  Fields:
    mimeType: A string attribute.
    sha1Sum: A string attribute.
    sourceUrl: A string attribute.
  """

  mimeType = _messages.StringField(1)
  sha1Sum = _messages.StringField(2)
  sourceUrl = _messages.StringField(3)


class GetIamPolicyRequest(_messages.Message):
  """A GetIamPolicyRequest object."""


class HealthCheck(_messages.Message):
  """A HealthCheck object.

  Fields:
    checkInterval: A string attribute.
    disableHealthCheck: A boolean attribute.
    healthyThreshold: A integer attribute.
    host: A string attribute.
    restartThreshold: A integer attribute.
    timeout: A string attribute.
    unhealthyThreshold: A integer attribute.
  """

  checkInterval = _messages.StringField(1)
  disableHealthCheck = _messages.BooleanField(2)
  healthyThreshold = _messages.IntegerField(3, variant=_messages.Variant.UINT32)
  host = _messages.StringField(4)
  restartThreshold = _messages.IntegerField(5, variant=_messages.Variant.UINT32)
  timeout = _messages.StringField(6)
  unhealthyThreshold = _messages.IntegerField(7, variant=_messages.Variant.UINT32)


class Library(_messages.Message):
  """A Library object.

  Fields:
    name: A string attribute.
    version: A string attribute.
  """

  name = _messages.StringField(1)
  version = _messages.StringField(2)


class ListEmailSendersResponse(_messages.Message):
  """A ListEmailSendersResponse object.

  Fields:
    emailSender: A EmailSender attribute.
    nextPageToken: A string attribute.
  """

  emailSender = _messages.MessageField('EmailSender', 1, repeated=True)
  nextPageToken = _messages.StringField(2)


class ListModulesResponse(_messages.Message):
  """A ListModulesResponse object.

  Fields:
    modules: A Module attribute.
    nextPageToken: A string attribute.
  """

  modules = _messages.MessageField('Module', 1, repeated=True)
  nextPageToken = _messages.StringField(2)


class ListOperationsResponse(_messages.Message):
  """A ListOperationsResponse object.

  Fields:
    nextPageToken: A string attribute.
    operations: A Operation attribute.
  """

  nextPageToken = _messages.StringField(1)
  operations = _messages.MessageField('Operation', 2, repeated=True)


class ListVersionsResponse(_messages.Message):
  """A ListVersionsResponse object.

  Fields:
    nextPageToken: A string attribute.
    versions: A Version attribute.
  """

  nextPageToken = _messages.StringField(1)
  versions = _messages.MessageField('Version', 2, repeated=True)


class LogConfig(_messages.Message):
  """A LogConfig object.

  Fields:
    cloudAudit: A CloudAuditOptions attribute.
    counter: A CounterOptions attribute.
    dataAccess: A DataAccessOptions attribute.
  """

  cloudAudit = _messages.MessageField('CloudAuditOptions', 1)
  counter = _messages.MessageField('CounterOptions', 2)
  dataAccess = _messages.MessageField('DataAccessOptions', 3)


class ManualScaling(_messages.Message):
  """A ManualScaling object.

  Fields:
    instances: A integer attribute.
  """

  instances = _messages.IntegerField(1, variant=_messages.Variant.INT32)


class Module(_messages.Message):
  """A Module object.

  Fields:
    id: A string attribute.
    name: A string attribute.
    split: A TrafficSplit attribute.
  """

  id = _messages.StringField(1)
  name = _messages.StringField(2)
  split = _messages.MessageField('TrafficSplit', 3)


class Network(_messages.Message):
  """A Network object.

  Fields:
    forwardedPorts: A string attribute.
    instanceTag: A string attribute.
    name: A string attribute.
  """

  forwardedPorts = _messages.StringField(1, repeated=True)
  instanceTag = _messages.StringField(2)
  name = _messages.StringField(3)


class Operation(_messages.Message):
  """A Operation object.

  Messages:
    MetadataValue: A MetadataValue object.
    ResponseValue: A ResponseValue object.

  Fields:
    done: A boolean attribute.
    error: A Status attribute.
    metadata: A MetadataValue attribute.
    name: A string attribute.
    response: A ResponseValue attribute.
  """

  @encoding.MapUnrecognizedFields('additionalProperties')
  class MetadataValue(_messages.Message):
    """A MetadataValue object.

    Messages:
      AdditionalProperty: An additional property for a MetadataValue object.

    Fields:
      additionalProperties: Additional properties of type MetadataValue
    """

    class AdditionalProperty(_messages.Message):
      """An additional property for a MetadataValue object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = _messages.StringField(1)
      value = _messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = _messages.MessageField('AdditionalProperty', 1, repeated=True)

  @encoding.MapUnrecognizedFields('additionalProperties')
  class ResponseValue(_messages.Message):
    """A ResponseValue object.

    Messages:
      AdditionalProperty: An additional property for a ResponseValue object.

    Fields:
      additionalProperties: Additional properties of type ResponseValue
    """

    class AdditionalProperty(_messages.Message):
      """An additional property for a ResponseValue object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = _messages.StringField(1)
      value = _messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = _messages.MessageField('AdditionalProperty', 1, repeated=True)

  done = _messages.BooleanField(1)
  error = _messages.MessageField('Status', 2)
  metadata = _messages.MessageField('MetadataValue', 3)
  name = _messages.StringField(4)
  response = _messages.MessageField('ResponseValue', 5)


class Policy(_messages.Message):
  """A Policy object.

  Fields:
    bindings: A Binding attribute.
    etag: A byte attribute.
    rules: A Rule attribute.
    version: A integer attribute.
  """

  bindings = _messages.MessageField('Binding', 1, repeated=True)
  etag = _messages.BytesField(2)
  rules = _messages.MessageField('Rule', 3, repeated=True)
  version = _messages.IntegerField(4, variant=_messages.Variant.INT32)


class Resources(_messages.Message):
  """A Resources object.

  Fields:
    cpu: A number attribute.
    diskGb: A number attribute.
    memoryGb: A number attribute.
  """

  cpu = _messages.FloatField(1)
  diskGb = _messages.FloatField(2)
  memoryGb = _messages.FloatField(3)


class Rule(_messages.Message):
  """A Rule object.

  Enums:
    ActionValueValuesEnum:

  Fields:
    action: A ActionValueValuesEnum attribute.
    conditions: A Condition attribute.
    description: A string attribute.
    in_: A string attribute.
    logConfig: A LogConfig attribute.
    notIn: A string attribute.
    permissions: A string attribute.
  """

  class ActionValueValuesEnum(_messages.Enum):
    """ActionValueValuesEnum enum type.

    Values:
      ALLOW: <no description>
      ALLOW_WITH_LOG: <no description>
      DENY: <no description>
      DENY_WITH_LOG: <no description>
      LOG: <no description>
      NO_ACTION: <no description>
    """
    ALLOW = 0
    ALLOW_WITH_LOG = 1
    DENY = 2
    DENY_WITH_LOG = 3
    LOG = 4
    NO_ACTION = 5

  action = _messages.EnumField('ActionValueValuesEnum', 1)
  conditions = _messages.MessageField('Condition', 2, repeated=True)
  description = _messages.StringField(3)
  in_ = _messages.StringField(4, repeated=True)
  logConfig = _messages.MessageField('LogConfig', 5, repeated=True)
  notIn = _messages.StringField(6, repeated=True)
  permissions = _messages.StringField(7, repeated=True)


class ScriptHandler(_messages.Message):
  """A ScriptHandler object.

  Fields:
    scriptPath: A string attribute.
  """

  scriptPath = _messages.StringField(1)


class SetIamPolicyRequest(_messages.Message):
  """A SetIamPolicyRequest object.

  Fields:
    policy: A Policy attribute.
  """

  policy = _messages.MessageField('Policy', 1)


class SourceReference(_messages.Message):
  """A SourceReference object.

  Fields:
    repository: A string attribute.
    revisionId: A string attribute.
  """

  repository = _messages.StringField(1)
  revisionId = _messages.StringField(2)


class StandardQueryParameters(_messages.Message):
  """Query parameters accepted by all methods.

  Enums:
    AltValueValuesEnum: Data format for the response.

  Fields:
    alt: Data format for the response.
    fields: Selector specifying which fields to include in a partial response.
    key: API key. Your API key identifies your project and provides you with
      API access, quota, and reports. Required unless you provide an OAuth 2.0
      token.
    oauth_token: OAuth 2.0 token for the current user.
    prettyPrint: Returns response with indentations and line breaks.
    quotaUser: Available to use for quota purposes for server-side
      applications. Can be any arbitrary string assigned to a user, but should
      not exceed 40 characters. Overrides userIp if both are provided.
    trace: A tracing token of the form "token:<tokenid>" or "email:<ldap>" to
      include in api requests.
    userIp: IP address of the site where the request originates. Use this if
      you want to enforce per-user limits.
  """

  class AltValueValuesEnum(_messages.Enum):
    """Data format for the response.

    Values:
      json: Responses with Content-Type of application/json
    """
    json = 0

  alt = _messages.EnumField('AltValueValuesEnum', 1, default=u'json')
  fields = _messages.StringField(2)
  key = _messages.StringField(3)
  oauth_token = _messages.StringField(4)
  prettyPrint = _messages.BooleanField(5, default=True)
  quotaUser = _messages.StringField(6)
  trace = _messages.StringField(7)
  userIp = _messages.StringField(8)


class StaticDirectoryHandler(_messages.Message):
  """A StaticDirectoryHandler object.

  Messages:
    HttpHeadersValue: A HttpHeadersValue object.

  Fields:
    applicationReadable: A boolean attribute.
    directory: A string attribute.
    expiration: A string attribute.
    httpHeaders: A HttpHeadersValue attribute.
    mimeType: A string attribute.
    requireMatchingFile: A boolean attribute.
  """

  @encoding.MapUnrecognizedFields('additionalProperties')
  class HttpHeadersValue(_messages.Message):
    """A HttpHeadersValue object.

    Messages:
      AdditionalProperty: An additional property for a HttpHeadersValue
        object.

    Fields:
      additionalProperties: Additional properties of type HttpHeadersValue
    """

    class AdditionalProperty(_messages.Message):
      """An additional property for a HttpHeadersValue object.

      Fields:
        key: Name of the additional property.
        value: A string attribute.
      """

      key = _messages.StringField(1)
      value = _messages.StringField(2)

    additionalProperties = _messages.MessageField('AdditionalProperty', 1, repeated=True)

  applicationReadable = _messages.BooleanField(1)
  directory = _messages.StringField(2)
  expiration = _messages.StringField(3)
  httpHeaders = _messages.MessageField('HttpHeadersValue', 4)
  mimeType = _messages.StringField(5)
  requireMatchingFile = _messages.BooleanField(6)


class StaticFilesHandler(_messages.Message):
  """A StaticFilesHandler object.

  Messages:
    HttpHeadersValue: A HttpHeadersValue object.

  Fields:
    applicationReadable: A boolean attribute.
    expiration: A string attribute.
    httpHeaders: A HttpHeadersValue attribute.
    mimeType: A string attribute.
    path: A string attribute.
    requireMatchingFile: A boolean attribute.
    uploadPathRegex: A string attribute.
  """

  @encoding.MapUnrecognizedFields('additionalProperties')
  class HttpHeadersValue(_messages.Message):
    """A HttpHeadersValue object.

    Messages:
      AdditionalProperty: An additional property for a HttpHeadersValue
        object.

    Fields:
      additionalProperties: Additional properties of type HttpHeadersValue
    """

    class AdditionalProperty(_messages.Message):
      """An additional property for a HttpHeadersValue object.

      Fields:
        key: Name of the additional property.
        value: A string attribute.
      """

      key = _messages.StringField(1)
      value = _messages.StringField(2)

    additionalProperties = _messages.MessageField('AdditionalProperty', 1, repeated=True)

  applicationReadable = _messages.BooleanField(1)
  expiration = _messages.StringField(2)
  httpHeaders = _messages.MessageField('HttpHeadersValue', 3)
  mimeType = _messages.StringField(4)
  path = _messages.StringField(5)
  requireMatchingFile = _messages.BooleanField(6)
  uploadPathRegex = _messages.StringField(7)


class Status(_messages.Message):
  """A Status object.

  Messages:
    DetailsValueListEntry: A DetailsValueListEntry object.

  Fields:
    code: A integer attribute.
    details: A DetailsValueListEntry attribute.
    message: A string attribute.
  """

  @encoding.MapUnrecognizedFields('additionalProperties')
  class DetailsValueListEntry(_messages.Message):
    """A DetailsValueListEntry object.

    Messages:
      AdditionalProperty: An additional property for a DetailsValueListEntry
        object.

    Fields:
      additionalProperties: Additional properties of type
        DetailsValueListEntry
    """

    class AdditionalProperty(_messages.Message):
      """An additional property for a DetailsValueListEntry object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = _messages.StringField(1)
      value = _messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = _messages.MessageField('AdditionalProperty', 1, repeated=True)

  code = _messages.IntegerField(1, variant=_messages.Variant.INT32)
  details = _messages.MessageField('DetailsValueListEntry', 2, repeated=True)
  message = _messages.StringField(3)


class TrafficSplit(_messages.Message):
  """A TrafficSplit object.

  Enums:
    ShardByValueValuesEnum:

  Messages:
    AllocationsValue: A AllocationsValue object.

  Fields:
    allocations: A AllocationsValue attribute.
    shardBy: A ShardByValueValuesEnum attribute.
  """

  class ShardByValueValuesEnum(_messages.Enum):
    """ShardByValueValuesEnum enum type.

    Values:
      COOKIE: <no description>
      IP: <no description>
      UNSPECIFIED: <no description>
    """
    COOKIE = 0
    IP = 1
    UNSPECIFIED = 2

  @encoding.MapUnrecognizedFields('additionalProperties')
  class AllocationsValue(_messages.Message):
    """A AllocationsValue object.

    Messages:
      AdditionalProperty: An additional property for a AllocationsValue
        object.

    Fields:
      additionalProperties: Additional properties of type AllocationsValue
    """

    class AdditionalProperty(_messages.Message):
      """An additional property for a AllocationsValue object.

      Fields:
        key: Name of the additional property.
        value: A number attribute.
      """

      key = _messages.StringField(1)
      value = _messages.FloatField(2)

    additionalProperties = _messages.MessageField('AdditionalProperty', 1, repeated=True)

  allocations = _messages.MessageField('AllocationsValue', 1)
  shardBy = _messages.EnumField('ShardByValueValuesEnum', 2)


class UrlDispatchRule(_messages.Message):
  """A UrlDispatchRule object.

  Fields:
    domain: A string attribute.
    module: A string attribute.
    path: A string attribute.
  """

  domain = _messages.StringField(1)
  module = _messages.StringField(2)
  path = _messages.StringField(3)


class UrlMap(_messages.Message):
  """A UrlMap object.

  Enums:
    AuthFailActionValueValuesEnum:
    LoginValueValuesEnum:
    RedirectHttpResponseCodeValueValuesEnum:
    SecurityLevelValueValuesEnum:

  Fields:
    apiEndpoint: A ApiEndpointHandler attribute.
    authFailAction: A AuthFailActionValueValuesEnum attribute.
    login: A LoginValueValuesEnum attribute.
    redirectHttpResponseCode: A RedirectHttpResponseCodeValueValuesEnum
      attribute.
    script: A ScriptHandler attribute.
    securityLevel: A SecurityLevelValueValuesEnum attribute.
    staticDirectory: A StaticDirectoryHandler attribute.
    staticFiles: A StaticFilesHandler attribute.
    urlRegex: A string attribute.
  """

  class AuthFailActionValueValuesEnum(_messages.Enum):
    """AuthFailActionValueValuesEnum enum type.

    Values:
      AUTH_FAIL_ACTION_REDIRECT: <no description>
      AUTH_FAIL_ACTION_UNAUTHORIZED: <no description>
      AUTH_FAIL_ACTION_UNSPECIFIED: <no description>
    """
    AUTH_FAIL_ACTION_REDIRECT = 0
    AUTH_FAIL_ACTION_UNAUTHORIZED = 1
    AUTH_FAIL_ACTION_UNSPECIFIED = 2

  class LoginValueValuesEnum(_messages.Enum):
    """LoginValueValuesEnum enum type.

    Values:
      LOGIN_ADMIN: <no description>
      LOGIN_OPTIONAL: <no description>
      LOGIN_REQUIRED: <no description>
      LOGIN_UNSPECIFIED: <no description>
    """
    LOGIN_ADMIN = 0
    LOGIN_OPTIONAL = 1
    LOGIN_REQUIRED = 2
    LOGIN_UNSPECIFIED = 3

  class RedirectHttpResponseCodeValueValuesEnum(_messages.Enum):
    """RedirectHttpResponseCodeValueValuesEnum enum type.

    Values:
      REDIRECT_HTTP_RESPONSE_CODE_301: <no description>
      REDIRECT_HTTP_RESPONSE_CODE_302: <no description>
      REDIRECT_HTTP_RESPONSE_CODE_303: <no description>
      REDIRECT_HTTP_RESPONSE_CODE_307: <no description>
      REDIRECT_HTTP_RESPONSE_CODE_UNSPECIFIED: <no description>
    """
    REDIRECT_HTTP_RESPONSE_CODE_301 = 0
    REDIRECT_HTTP_RESPONSE_CODE_302 = 1
    REDIRECT_HTTP_RESPONSE_CODE_303 = 2
    REDIRECT_HTTP_RESPONSE_CODE_307 = 3
    REDIRECT_HTTP_RESPONSE_CODE_UNSPECIFIED = 4

  class SecurityLevelValueValuesEnum(_messages.Enum):
    """SecurityLevelValueValuesEnum enum type.

    Values:
      SECURE_ALWAYS: <no description>
      SECURE_DEFAULT: <no description>
      SECURE_NEVER: <no description>
      SECURE_OPTIONAL: <no description>
      SECURE_UNSPECIFIED: <no description>
    """
    SECURE_ALWAYS = 0
    SECURE_DEFAULT = 1
    SECURE_NEVER = 2
    SECURE_OPTIONAL = 3
    SECURE_UNSPECIFIED = 4

  apiEndpoint = _messages.MessageField('ApiEndpointHandler', 1)
  authFailAction = _messages.EnumField('AuthFailActionValueValuesEnum', 2)
  login = _messages.EnumField('LoginValueValuesEnum', 3)
  redirectHttpResponseCode = _messages.EnumField('RedirectHttpResponseCodeValueValuesEnum', 4)
  script = _messages.MessageField('ScriptHandler', 5)
  securityLevel = _messages.EnumField('SecurityLevelValueValuesEnum', 6)
  staticDirectory = _messages.MessageField('StaticDirectoryHandler', 7)
  staticFiles = _messages.MessageField('StaticFilesHandler', 8)
  urlRegex = _messages.StringField(9)


class Version(_messages.Message):
  """A Version object.

  Enums:
    InboundServicesValueListEntryValuesEnum:

  Messages:
    BetaSettingsValue: A BetaSettingsValue object.
    EnvVariablesValue: A EnvVariablesValue object.

  Fields:
    apiConfig: A ApiConfigHandler attribute.
    automaticScaling: A AutomaticScaling attribute.
    basicScaling: A BasicScaling attribute.
    betaSettings: A BetaSettingsValue attribute.
    defaultExpiration: A string attribute.
    deployment: A Deployment attribute.
    envVariables: A EnvVariablesValue attribute.
    errorHandlers: A ErrorHandler attribute.
    handlers: A UrlMap attribute.
    healthCheck: A HealthCheck attribute.
    id: A string attribute.
    inboundServices: A InboundServicesValueListEntryValuesEnum attribute.
    instanceClass: A string attribute.
    libraries: A Library attribute.
    manualScaling: A ManualScaling attribute.
    name: A string attribute.
    network: A Network attribute.
    nobuildFilesRegex: A string attribute.
    resources: A Resources attribute.
    runtime: A string attribute.
    threadsafe: A boolean attribute.
    vm: A boolean attribute.
  """

  class InboundServicesValueListEntryValuesEnum(_messages.Enum):
    """InboundServicesValueListEntryValuesEnum enum type.

    Values:
      INBOUND_SERVICE_CHANNEL_PRESENCE: <no description>
      INBOUND_SERVICE_MAIL: <no description>
      INBOUND_SERVICE_MAIL_BOUNCE: <no description>
      INBOUND_SERVICE_REST: <no description>
      INBOUND_SERVICE_UNSPECIFIED: <no description>
      INBOUND_SERVICE_WARMUP: <no description>
      INBOUND_SERVICE_XMPP_ERROR: <no description>
      INBOUND_SERVICE_XMPP_MESSAGE: <no description>
      INBOUND_SERVICE_XMPP_PRESENCE: <no description>
      INBOUND_SERVICE_XMPP_SUBSCRIBE: <no description>
    """
    INBOUND_SERVICE_CHANNEL_PRESENCE = 0
    INBOUND_SERVICE_MAIL = 1
    INBOUND_SERVICE_MAIL_BOUNCE = 2
    INBOUND_SERVICE_REST = 3
    INBOUND_SERVICE_UNSPECIFIED = 4
    INBOUND_SERVICE_WARMUP = 5
    INBOUND_SERVICE_XMPP_ERROR = 6
    INBOUND_SERVICE_XMPP_MESSAGE = 7
    INBOUND_SERVICE_XMPP_PRESENCE = 8
    INBOUND_SERVICE_XMPP_SUBSCRIBE = 9

  @encoding.MapUnrecognizedFields('additionalProperties')
  class BetaSettingsValue(_messages.Message):
    """A BetaSettingsValue object.

    Messages:
      AdditionalProperty: An additional property for a BetaSettingsValue
        object.

    Fields:
      additionalProperties: Additional properties of type BetaSettingsValue
    """

    class AdditionalProperty(_messages.Message):
      """An additional property for a BetaSettingsValue object.

      Fields:
        key: Name of the additional property.
        value: A string attribute.
      """

      key = _messages.StringField(1)
      value = _messages.StringField(2)

    additionalProperties = _messages.MessageField('AdditionalProperty', 1, repeated=True)

  @encoding.MapUnrecognizedFields('additionalProperties')
  class EnvVariablesValue(_messages.Message):
    """A EnvVariablesValue object.

    Messages:
      AdditionalProperty: An additional property for a EnvVariablesValue
        object.

    Fields:
      additionalProperties: Additional properties of type EnvVariablesValue
    """

    class AdditionalProperty(_messages.Message):
      """An additional property for a EnvVariablesValue object.

      Fields:
        key: Name of the additional property.
        value: A string attribute.
      """

      key = _messages.StringField(1)
      value = _messages.StringField(2)

    additionalProperties = _messages.MessageField('AdditionalProperty', 1, repeated=True)

  apiConfig = _messages.MessageField('ApiConfigHandler', 1)
  automaticScaling = _messages.MessageField('AutomaticScaling', 2)
  basicScaling = _messages.MessageField('BasicScaling', 3)
  betaSettings = _messages.MessageField('BetaSettingsValue', 4)
  defaultExpiration = _messages.StringField(5)
  deployment = _messages.MessageField('Deployment', 6)
  envVariables = _messages.MessageField('EnvVariablesValue', 7)
  errorHandlers = _messages.MessageField('ErrorHandler', 8, repeated=True)
  handlers = _messages.MessageField('UrlMap', 9, repeated=True)
  healthCheck = _messages.MessageField('HealthCheck', 10)
  id = _messages.StringField(11)
  inboundServices = _messages.EnumField('InboundServicesValueListEntryValuesEnum', 12, repeated=True)
  instanceClass = _messages.StringField(13)
  libraries = _messages.MessageField('Library', 14, repeated=True)
  manualScaling = _messages.MessageField('ManualScaling', 15)
  name = _messages.StringField(16)
  network = _messages.MessageField('Network', 17)
  nobuildFilesRegex = _messages.StringField(18)
  resources = _messages.MessageField('Resources', 19)
  runtime = _messages.StringField(20)
  threadsafe = _messages.BooleanField(21)
  vm = _messages.BooleanField(22)


encoding.AddCustomJsonFieldMapping(
    Rule, 'in_', 'in',
    package=u'appengine')
